//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiylanEtl.InventChildService.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="Proxy.ZRT_ENT_PERAPORT")]
    internal interface ZRT_ENT_PERAPORT {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZRT_ENT_PERAPORT:ZrtEntPeraportR" +
            "equest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportResponse1 ZrtEntPeraport(ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZRT_ENT_PERAPORT:ZrtEntPeraportR" +
            "equest", ReplyAction="*")]
        System.Threading.Tasks.Task<ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportResponse1> ZrtEntPeraportAsync(ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZrtEntPeraport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string c1Field;
        
        private string c2Field;
        
        private string c3Field;
        
        private string c4Field;
        
        private string c5Field;
        
        private string c6Field;
        
        private string c7Field;
        
        private string c8Field;
        
        private string c9Field;
        
        private string erdatField;
        
        private ZinventAsorti[] gtZinventAsortiField;
        
        private ZinventFyt[] gtZinventFytField;
        
        private ZinventHrk[] gtZinventHrkField;
        
        private ZinventMlz[] gtZinventMlzField;
        
        private ZinventStok[] gtZinventStokField;
        
        private ZinventStokA[] gtZinventStokAField;
        
        private ZinventTes[] gtZinventTesField;
        
        private ZinventTrn[] gtZinventTrnField;
        
        private ZinventUy[] gtZinventUyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string C1 {
            get {
                return this.c1Field;
            }
            set {
                this.c1Field = value;
                this.RaisePropertyChanged("C1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string C2 {
            get {
                return this.c2Field;
            }
            set {
                this.c2Field = value;
                this.RaisePropertyChanged("C2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string C3 {
            get {
                return this.c3Field;
            }
            set {
                this.c3Field = value;
                this.RaisePropertyChanged("C3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string C4 {
            get {
                return this.c4Field;
            }
            set {
                this.c4Field = value;
                this.RaisePropertyChanged("C4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string C5 {
            get {
                return this.c5Field;
            }
            set {
                this.c5Field = value;
                this.RaisePropertyChanged("C5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string C6 {
            get {
                return this.c6Field;
            }
            set {
                this.c6Field = value;
                this.RaisePropertyChanged("C6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string C7 {
            get {
                return this.c7Field;
            }
            set {
                this.c7Field = value;
                this.RaisePropertyChanged("C7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string C8 {
            get {
                return this.c8Field;
            }
            set {
                this.c8Field = value;
                this.RaisePropertyChanged("C8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string C9 {
            get {
                return this.c9Field;
            }
            set {
                this.c9Field = value;
                this.RaisePropertyChanged("C9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventAsorti[] GtZinventAsorti {
            get {
                return this.gtZinventAsortiField;
            }
            set {
                this.gtZinventAsortiField = value;
                this.RaisePropertyChanged("GtZinventAsorti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventFyt[] GtZinventFyt {
            get {
                return this.gtZinventFytField;
            }
            set {
                this.gtZinventFytField = value;
                this.RaisePropertyChanged("GtZinventFyt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventHrk[] GtZinventHrk {
            get {
                return this.gtZinventHrkField;
            }
            set {
                this.gtZinventHrkField = value;
                this.RaisePropertyChanged("GtZinventHrk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventMlz[] GtZinventMlz {
            get {
                return this.gtZinventMlzField;
            }
            set {
                this.gtZinventMlzField = value;
                this.RaisePropertyChanged("GtZinventMlz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventStok[] GtZinventStok {
            get {
                return this.gtZinventStokField;
            }
            set {
                this.gtZinventStokField = value;
                this.RaisePropertyChanged("GtZinventStok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventStokA[] GtZinventStokA {
            get {
                return this.gtZinventStokAField;
            }
            set {
                this.gtZinventStokAField = value;
                this.RaisePropertyChanged("GtZinventStokA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventTes[] GtZinventTes {
            get {
                return this.gtZinventTesField;
            }
            set {
                this.gtZinventTesField = value;
                this.RaisePropertyChanged("GtZinventTes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventTrn[] GtZinventTrn {
            get {
                return this.gtZinventTrnField;
            }
            set {
                this.gtZinventTrnField = value;
                this.RaisePropertyChanged("GtZinventTrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventUy[] GtZinventUy {
            get {
                return this.gtZinventUyField;
            }
            set {
                this.gtZinventUyField = value;
                this.RaisePropertyChanged("GtZinventUy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventAsorti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string idnrkField;
        
        private string matnrField;
        
        private decimal mengeField;
        
        private string zzkolitipiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Idnrk {
            get {
                return this.idnrkField;
            }
            set {
                this.idnrkField = value;
                this.RaisePropertyChanged("Idnrk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Menge {
            get {
                return this.mengeField;
            }
            set {
                this.mengeField = value;
                this.RaisePropertyChanged("Menge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Zzkolitipi {
            get {
                return this.zzkolitipiField;
            }
            set {
                this.zzkolitipiField = value;
                this.RaisePropertyChanged("Zzkolitipi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventUy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string werksField;
        
        private string land1Field;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string betrpField;
        
        private string extension2Field;
        
        private string brschField;
        
        private string bzirkField;
        
        private string eroedField;
        
        private string schldField;
        
        private string name1Field;
        
        private string sort1Field;
        
        private string sort2Field;
        
        private string mcCity1Field;
        
        private decimal verflField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Land1 {
            get {
                return this.land1Field;
            }
            set {
                this.land1Field = value;
                this.RaisePropertyChanged("Land1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Betrp {
            get {
                return this.betrpField;
            }
            set {
                this.betrpField = value;
                this.RaisePropertyChanged("Betrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Extension2 {
            get {
                return this.extension2Field;
            }
            set {
                this.extension2Field = value;
                this.RaisePropertyChanged("Extension2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Brsch {
            get {
                return this.brschField;
            }
            set {
                this.brschField = value;
                this.RaisePropertyChanged("Brsch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Bzirk {
            get {
                return this.bzirkField;
            }
            set {
                this.bzirkField = value;
                this.RaisePropertyChanged("Bzirk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Eroed {
            get {
                return this.eroedField;
            }
            set {
                this.eroedField = value;
                this.RaisePropertyChanged("Eroed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Schld {
            get {
                return this.schldField;
            }
            set {
                this.schldField = value;
                this.RaisePropertyChanged("Schld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
                this.RaisePropertyChanged("Name1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Sort1 {
            get {
                return this.sort1Field;
            }
            set {
                this.sort1Field = value;
                this.RaisePropertyChanged("Sort1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Sort2 {
            get {
                return this.sort2Field;
            }
            set {
                this.sort2Field = value;
                this.RaisePropertyChanged("Sort2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string McCity1 {
            get {
                return this.mcCity1Field;
            }
            set {
                this.mcCity1Field = value;
                this.RaisePropertyChanged("McCity1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal Verfl {
            get {
                return this.verflField;
            }
            set {
                this.verflField = value;
                this.RaisePropertyChanged("Verfl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventTrn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string aedatField;
        
        private string reswkField;
        
        private string werksField;
        
        private string zzcdepoField;
        
        private string bsartField;
        
        private string matnrField;
        
        private decimal pomengeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Aedat {
            get {
                return this.aedatField;
            }
            set {
                this.aedatField = value;
                this.RaisePropertyChanged("Aedat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Reswk {
            get {
                return this.reswkField;
            }
            set {
                this.reswkField = value;
                this.RaisePropertyChanged("Reswk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Zzcdepo {
            get {
                return this.zzcdepoField;
            }
            set {
                this.zzcdepoField = value;
                this.RaisePropertyChanged("Zzcdepo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Bsart {
            get {
                return this.bsartField;
            }
            set {
                this.bsartField = value;
                this.RaisePropertyChanged("Bsart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Pomenge {
            get {
                return this.pomengeField;
            }
            set {
                this.pomengeField = value;
                this.RaisePropertyChanged("Pomenge");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventTes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string vbelnField;
        
        private string posnrField;
        
        private string ebelnField;
        
        private string cpudtField;
        
        private string matnrField;
        
        private decimal lfimgField;
        
        private string meinsField;
        
        private string werksField;
        
        private string lgortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
                this.RaisePropertyChanged("Vbeln");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Posnr {
            get {
                return this.posnrField;
            }
            set {
                this.posnrField = value;
                this.RaisePropertyChanged("Posnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Ebeln {
            get {
                return this.ebelnField;
            }
            set {
                this.ebelnField = value;
                this.RaisePropertyChanged("Ebeln");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Cpudt {
            get {
                return this.cpudtField;
            }
            set {
                this.cpudtField = value;
                this.RaisePropertyChanged("Cpudt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Lfimg {
            get {
                return this.lfimgField;
            }
            set {
                this.lfimgField = value;
                this.RaisePropertyChanged("Lfimg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Meins {
            get {
                return this.meinsField;
            }
            set {
                this.meinsField = value;
                this.RaisePropertyChanged("Meins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
                this.RaisePropertyChanged("Lgort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventStokA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string matnrField;
        
        private string werksField;
        
        private string lgortField;
        
        private decimal atpField;
        
        private decimal aciksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
                this.RaisePropertyChanged("Lgort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Atp {
            get {
                return this.atpField;
            }
            set {
                this.atpField = value;
                this.RaisePropertyChanged("Atp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Aciks {
            get {
                return this.aciksField;
            }
            set {
                this.aciksField = value;
                this.RaisePropertyChanged("Aciks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventStok : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string matnrField;
        
        private string werksField;
        
        private string lgortField;
        
        private decimal atpField;
        
        private decimal aciksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
                this.RaisePropertyChanged("Lgort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Atp {
            get {
                return this.atpField;
            }
            set {
                this.atpField = value;
                this.RaisePropertyChanged("Atp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Aciks {
            get {
                return this.aciksField;
            }
            set {
                this.aciksField = value;
                this.RaisePropertyChanged("Aciks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventMlz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string idnrkField;
        
        private string satnrField;
        
        private string maktxField;
        
        private string size1Field;
        
        private string matklField;
        
        private string brandIdField;
        
        private string bismtField;
        
        private string zzeslenikField;
        
        private string zzvipField;
        
        private string wekgrField;
        
        private string saisoField;
        
        private string saisjField;
        
        private string laborField;
        
        private string zzmodelField;
        
        private string zzrenkaField;
        
        private string zzrenk2Field;
        
        private string zzrenk3Field;
        
        private string zzfytgrField;
        
        private string zzamarkField;
        
        private string zzcnsytField;
        
        private string zzbdngrField;
        
        private string zzmenseField;
        
        private string zzktaskField;
        
        private string zzoutltField;
        
        private string zzouttrField;
        
        private string zzzlineField;
        
        private string zzsezonField;
        
        private string zzszyilField;
        
        private string zzszdgsField;
        
        private string zzurunField;
        
        private string zzstkgrField;
        
        private string zzkmpr1Field;
        
        private string zzkmpr2Field;
        
        private string zzkmpr3Field;
        
        private string zzkmpr4Field;
        
        private string zzkmpr5Field;
        
        private string zzomurbField;
        
        private string zzomurbtField;
        
        private string bwsclField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Idnrk {
            get {
                return this.idnrkField;
            }
            set {
                this.idnrkField = value;
                this.RaisePropertyChanged("Idnrk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Satnr {
            get {
                return this.satnrField;
            }
            set {
                this.satnrField = value;
                this.RaisePropertyChanged("Satnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Maktx {
            get {
                return this.maktxField;
            }
            set {
                this.maktxField = value;
                this.RaisePropertyChanged("Maktx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Size1 {
            get {
                return this.size1Field;
            }
            set {
                this.size1Field = value;
                this.RaisePropertyChanged("Size1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Matkl {
            get {
                return this.matklField;
            }
            set {
                this.matklField = value;
                this.RaisePropertyChanged("Matkl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BrandId {
            get {
                return this.brandIdField;
            }
            set {
                this.brandIdField = value;
                this.RaisePropertyChanged("BrandId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Bismt {
            get {
                return this.bismtField;
            }
            set {
                this.bismtField = value;
                this.RaisePropertyChanged("Bismt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Zzeslenik {
            get {
                return this.zzeslenikField;
            }
            set {
                this.zzeslenikField = value;
                this.RaisePropertyChanged("Zzeslenik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Zzvip {
            get {
                return this.zzvipField;
            }
            set {
                this.zzvipField = value;
                this.RaisePropertyChanged("Zzvip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Wekgr {
            get {
                return this.wekgrField;
            }
            set {
                this.wekgrField = value;
                this.RaisePropertyChanged("Wekgr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Saiso {
            get {
                return this.saisoField;
            }
            set {
                this.saisoField = value;
                this.RaisePropertyChanged("Saiso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Saisj {
            get {
                return this.saisjField;
            }
            set {
                this.saisjField = value;
                this.RaisePropertyChanged("Saisj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Labor {
            get {
                return this.laborField;
            }
            set {
                this.laborField = value;
                this.RaisePropertyChanged("Labor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Zzmodel {
            get {
                return this.zzmodelField;
            }
            set {
                this.zzmodelField = value;
                this.RaisePropertyChanged("Zzmodel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Zzrenka {
            get {
                return this.zzrenkaField;
            }
            set {
                this.zzrenkaField = value;
                this.RaisePropertyChanged("Zzrenka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Zzrenk2 {
            get {
                return this.zzrenk2Field;
            }
            set {
                this.zzrenk2Field = value;
                this.RaisePropertyChanged("Zzrenk2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Zzrenk3 {
            get {
                return this.zzrenk3Field;
            }
            set {
                this.zzrenk3Field = value;
                this.RaisePropertyChanged("Zzrenk3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Zzfytgr {
            get {
                return this.zzfytgrField;
            }
            set {
                this.zzfytgrField = value;
                this.RaisePropertyChanged("Zzfytgr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Zzamark {
            get {
                return this.zzamarkField;
            }
            set {
                this.zzamarkField = value;
                this.RaisePropertyChanged("Zzamark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Zzcnsyt {
            get {
                return this.zzcnsytField;
            }
            set {
                this.zzcnsytField = value;
                this.RaisePropertyChanged("Zzcnsyt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Zzbdngr {
            get {
                return this.zzbdngrField;
            }
            set {
                this.zzbdngrField = value;
                this.RaisePropertyChanged("Zzbdngr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Zzmense {
            get {
                return this.zzmenseField;
            }
            set {
                this.zzmenseField = value;
                this.RaisePropertyChanged("Zzmense");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Zzktask {
            get {
                return this.zzktaskField;
            }
            set {
                this.zzktaskField = value;
                this.RaisePropertyChanged("Zzktask");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Zzoutlt {
            get {
                return this.zzoutltField;
            }
            set {
                this.zzoutltField = value;
                this.RaisePropertyChanged("Zzoutlt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Zzouttr {
            get {
                return this.zzouttrField;
            }
            set {
                this.zzouttrField = value;
                this.RaisePropertyChanged("Zzouttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Zzzline {
            get {
                return this.zzzlineField;
            }
            set {
                this.zzzlineField = value;
                this.RaisePropertyChanged("Zzzline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Zzsezon {
            get {
                return this.zzsezonField;
            }
            set {
                this.zzsezonField = value;
                this.RaisePropertyChanged("Zzsezon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Zzszyil {
            get {
                return this.zzszyilField;
            }
            set {
                this.zzszyilField = value;
                this.RaisePropertyChanged("Zzszyil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Zzszdgs {
            get {
                return this.zzszdgsField;
            }
            set {
                this.zzszdgsField = value;
                this.RaisePropertyChanged("Zzszdgs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Zzurun {
            get {
                return this.zzurunField;
            }
            set {
                this.zzurunField = value;
                this.RaisePropertyChanged("Zzurun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Zzstkgr {
            get {
                return this.zzstkgrField;
            }
            set {
                this.zzstkgrField = value;
                this.RaisePropertyChanged("Zzstkgr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Zzkmpr1 {
            get {
                return this.zzkmpr1Field;
            }
            set {
                this.zzkmpr1Field = value;
                this.RaisePropertyChanged("Zzkmpr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string Zzkmpr2 {
            get {
                return this.zzkmpr2Field;
            }
            set {
                this.zzkmpr2Field = value;
                this.RaisePropertyChanged("Zzkmpr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Zzkmpr3 {
            get {
                return this.zzkmpr3Field;
            }
            set {
                this.zzkmpr3Field = value;
                this.RaisePropertyChanged("Zzkmpr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Zzkmpr4 {
            get {
                return this.zzkmpr4Field;
            }
            set {
                this.zzkmpr4Field = value;
                this.RaisePropertyChanged("Zzkmpr4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Zzkmpr5 {
            get {
                return this.zzkmpr5Field;
            }
            set {
                this.zzkmpr5Field = value;
                this.RaisePropertyChanged("Zzkmpr5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Zzomurb {
            get {
                return this.zzomurbField;
            }
            set {
                this.zzomurbField = value;
                this.RaisePropertyChanged("Zzomurb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string Zzomurbt {
            get {
                return this.zzomurbtField;
            }
            set {
                this.zzomurbtField = value;
                this.RaisePropertyChanged("Zzomurbt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string Bwscl {
            get {
                return this.bwsclField;
            }
            set {
                this.bwsclField = value;
                this.RaisePropertyChanged("Bwscl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventHrk : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string budatField;
        
        private string zzhareketkoduField;
        
        private string zzterskayitField;
        
        private string werksField;
        
        private string lgortField;
        
        private string umwrkField;
        
        private string matnrField;
        
        private decimal erfmgField;
        
        private decimal dmbtrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Budat {
            get {
                return this.budatField;
            }
            set {
                this.budatField = value;
                this.RaisePropertyChanged("Budat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Zzhareketkodu {
            get {
                return this.zzhareketkoduField;
            }
            set {
                this.zzhareketkoduField = value;
                this.RaisePropertyChanged("Zzhareketkodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Zzterskayit {
            get {
                return this.zzterskayitField;
            }
            set {
                this.zzterskayitField = value;
                this.RaisePropertyChanged("Zzterskayit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Werks {
            get {
                return this.werksField;
            }
            set {
                this.werksField = value;
                this.RaisePropertyChanged("Werks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Lgort {
            get {
                return this.lgortField;
            }
            set {
                this.lgortField = value;
                this.RaisePropertyChanged("Lgort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Umwrk {
            get {
                return this.umwrkField;
            }
            set {
                this.umwrkField = value;
                this.RaisePropertyChanged("Umwrk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Erfmg {
            get {
                return this.erfmgField;
            }
            set {
                this.erfmgField = value;
                this.RaisePropertyChanged("Erfmg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Dmbtr {
            get {
                return this.dmbtrField;
            }
            set {
                this.dmbtrField = value;
                this.RaisePropertyChanged("Dmbtr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinventFyt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandtField;
        
        private string erdatField;
        
        private string matnrField;
        
        private string vkorgField;
        
        private string vtwegField;
        
        private string ekorgField;
        
        private string databField;
        
        private decimal pb00Field;
        
        private decimal z002Field;
        
        private decimal z003Field;
        
        private decimal z004Field;
        
        private decimal z005Field;
        
        private decimal z006Field;
        
        private decimal z007Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
                this.RaisePropertyChanged("Mandt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
                this.RaisePropertyChanged("Erdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
                this.RaisePropertyChanged("Matnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Vkorg {
            get {
                return this.vkorgField;
            }
            set {
                this.vkorgField = value;
                this.RaisePropertyChanged("Vkorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Vtweg {
            get {
                return this.vtwegField;
            }
            set {
                this.vtwegField = value;
                this.RaisePropertyChanged("Vtweg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Ekorg {
            get {
                return this.ekorgField;
            }
            set {
                this.ekorgField = value;
                this.RaisePropertyChanged("Ekorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Datab {
            get {
                return this.databField;
            }
            set {
                this.databField = value;
                this.RaisePropertyChanged("Datab");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Pb00 {
            get {
                return this.pb00Field;
            }
            set {
                this.pb00Field = value;
                this.RaisePropertyChanged("Pb00");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal z002 {
            get {
                return this.z002Field;
            }
            set {
                this.z002Field = value;
                this.RaisePropertyChanged("z002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal z003 {
            get {
                return this.z003Field;
            }
            set {
                this.z003Field = value;
                this.RaisePropertyChanged("z003");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal z004 {
            get {
                return this.z004Field;
            }
            set {
                this.z004Field = value;
                this.RaisePropertyChanged("z004");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal z005 {
            get {
                return this.z005Field;
            }
            set {
                this.z005Field = value;
                this.RaisePropertyChanged("z005");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal z006 {
            get {
                return this.z006Field;
            }
            set {
                this.z006Field = value;
                this.RaisePropertyChanged("z006");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal z007 {
            get {
                return this.z007Field;
            }
            set {
                this.z007Field = value;
                this.RaisePropertyChanged("z007");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZrtEntPeraportResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZinventAsorti[] gtZinventAsortiField;
        
        private ZinventFyt[] gtZinventFytField;
        
        private ZinventHrk[] gtZinventHrkField;
        
        private ZinventMlz[] gtZinventMlzField;
        
        private ZinventStok[] gtZinventStokField;
        
        private ZinventStokA[] gtZinventStokAField;
        
        private ZinventTes[] gtZinventTesField;
        
        private ZinventTrn[] gtZinventTrnField;
        
        private ZinventUy[] gtZinventUyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventAsorti[] GtZinventAsorti {
            get {
                return this.gtZinventAsortiField;
            }
            set {
                this.gtZinventAsortiField = value;
                this.RaisePropertyChanged("GtZinventAsorti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventFyt[] GtZinventFyt {
            get {
                return this.gtZinventFytField;
            }
            set {
                this.gtZinventFytField = value;
                this.RaisePropertyChanged("GtZinventFyt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventHrk[] GtZinventHrk {
            get {
                return this.gtZinventHrkField;
            }
            set {
                this.gtZinventHrkField = value;
                this.RaisePropertyChanged("GtZinventHrk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventMlz[] GtZinventMlz {
            get {
                return this.gtZinventMlzField;
            }
            set {
                this.gtZinventMlzField = value;
                this.RaisePropertyChanged("GtZinventMlz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventStok[] GtZinventStok {
            get {
                return this.gtZinventStokField;
            }
            set {
                this.gtZinventStokField = value;
                this.RaisePropertyChanged("GtZinventStok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventStokA[] GtZinventStokA {
            get {
                return this.gtZinventStokAField;
            }
            set {
                this.gtZinventStokAField = value;
                this.RaisePropertyChanged("GtZinventStokA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventTes[] GtZinventTes {
            get {
                return this.gtZinventTesField;
            }
            set {
                this.gtZinventTesField = value;
                this.RaisePropertyChanged("GtZinventTes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventTrn[] GtZinventTrn {
            get {
                return this.gtZinventTrnField;
            }
            set {
                this.gtZinventTrnField = value;
                this.RaisePropertyChanged("GtZinventTrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinventUy[] GtZinventUy {
            get {
                return this.gtZinventUyField;
            }
            set {
                this.gtZinventUyField = value;
                this.RaisePropertyChanged("GtZinventUy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZrtEntPeraportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ZiylanEtl.InventChildService.Proxy.ZrtEntPeraport ZrtEntPeraport;
        
        public ZrtEntPeraportRequest() {
        }
        
        public ZrtEntPeraportRequest(ZiylanEtl.InventChildService.Proxy.ZrtEntPeraport ZrtEntPeraport) {
            this.ZrtEntPeraport = ZrtEntPeraport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZrtEntPeraportResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportResponse ZrtEntPeraportResponse;
        
        public ZrtEntPeraportResponse1() {
        }
        
        public ZrtEntPeraportResponse1(ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportResponse ZrtEntPeraportResponse) {
            this.ZrtEntPeraportResponse = ZrtEntPeraportResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ZRT_ENT_PERAPORTChannel : ZiylanEtl.InventChildService.Proxy.ZRT_ENT_PERAPORT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ZRT_ENT_PERAPORTClient : System.ServiceModel.ClientBase<ZiylanEtl.InventChildService.Proxy.ZRT_ENT_PERAPORT>, ZiylanEtl.InventChildService.Proxy.ZRT_ENT_PERAPORT {
        
        public ZRT_ENT_PERAPORTClient() {
        }
        
        public ZRT_ENT_PERAPORTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZRT_ENT_PERAPORTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZRT_ENT_PERAPORTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZRT_ENT_PERAPORTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportResponse1 ZrtEntPeraport(ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportRequest request) {
            return base.Channel.ZrtEntPeraport(request);
        }
        
        public System.Threading.Tasks.Task<ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportResponse1> ZrtEntPeraportAsync(ZiylanEtl.InventChildService.Proxy.ZrtEntPeraportRequest request) {
            return base.Channel.ZrtEntPeraportAsync(request);
        }
    }
}
